# c("arrow","DBI","dbplyr","dials","dplyr","glue","hardhat","jsonlite","parsnip",
# "purrr","R6","recipes","rlang","RSQLite","stats","tidyr","withr", "kernlab",
# "lifecycle", "cli")

# c("covr", "dm", "here", "knitr", "rmarkdown", "testthat")
# setwd("~/project/rpwf")

# Depends:
#   R (>= 2.10)
# rpwf_cp_py_codes("C:\\vbox-shared\\projects\\python_test", overwrite = TRUE)

# https://github.com/acheronfail/repgrep
# rgr rpwf_sim .

# * Here is the structure of the `"db.SQLite"` database:
#   + `model_type_tbl` holds the definitions required to translate the models
# defined in `{tidymodels}` into models defined in `scikit-learn`
# + `r_grid_tbl` holds the hyper parameters grid generated by the [`{dials}`](https://dials.tidymodels.org/) package.
# + `df_tbl` holds the transformed data generated by the [`{recipes}`](https://recipes.tidymodels.org/) package.
# + `wflow_tbl` holds the different workflows.
# + `wflow_result_tbl` holds the fitted results of the workflows.
#
# ```{r, fig.align='center', fig.width=6, fig.height=6}
# dm_obj <- rpwf_dm(db_con)
# dm_obj |>
#   dm::dm_draw()
# ```
