#' Add information about the python module
#'
#' Augment the model spec object generated by `{parsnip}` with information
#' needed to run sklearn models
#'
#' @param obj a model spec object generated by [parsnip::set_engine()] and
#' [parsnip::set_mode()]
#' @param py_base_learner a character value that select the python base learner,
#' (i.e., XGBClassifier, DecisionTreeClassifier, etc.)
#' @param con optional [DBI::dbConnect()] object created by [rpwf::rpwf_db_con()].
#' If provided will perform check if the py_base_learner is in the database or not.
#' @param args arguments passed to the python base learner. Booleans should be
#' in R format (TRUE, FALSE). Must be in named list.
#'
#' @return a model spec object with additional attributes `self$py_base_learner`
#' and `self$py_base_learner_args`
#' @export
#'
#' @examples
#' con = rpwf_db_con("db.SQLite", here::here())
#' parsnip::boost_tree() |>
#' parsnip::set_engine("xgboost") |>
#' parsnip::set_mode("classification") |>
#' set_py_engine("XGBClassifier", con,
#'               list(eval_metric = "logloss", use_label_encoder = FALSE,
#'                    verbosity = 0, silent = TRUE))
set_py_engine = function(obj, py_base_learner, con = NULL, args = NULL) {
  if(!is.null(con)){
    avail = DBI::dbGetQuery(
      con, 'SELECT py_base_learner FROM model_type_tbl')$py_base_learner
    if (!py_base_learner %in% avail) {
      cat(paste(avail, collapse = ", "))
      cat("\n")
      stop("Select from the above models")
    }
  }
  obj$py_base_learner = py_base_learner

  if (!is.null(args)) {
    stopifnot("Use named list for py learner args" =
                all("list" %in% class(args)) & !is.null(names(args)))
    obj$py_base_learner_args = jsonlite::toJSON(args, auto_unbox = TRUE)
  }
  return(obj)
}
